### ISSUE TITLE
Static toString is taking precedence during expression evaluation result logging

### ISSUE THREAD

**Issue by apryamostanov** [INFINITE-TECHNOLOGY/BLACKBOX#17]
The below code:
```groovy
package io.infinite.blackbox.others

class StaticToString {

    static String toString() {
        throw new Exception("should not be called!")
    }

}
        BlackBoxEngine.getInstance().expressionEvaluation("","", 0, 0, 0, 0, {StaticToString}, "")
```

Fails with exception:

```
Exception in thread "main" java.lang.Exception: should not be called!
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:250)
	at io.infinite.blackbox.others.StaticToString.toString(StaticToString.groovy:6)
	at io.infinite.blackbox.others.StaticToString$toString.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at java_lang_CharSequence$toString.call(Unknown Source)
	at io.infinite.blackbox.BlackBoxEngine.expressionEvaluation(BlackBoxEngine.groovy:161)
	at io.infinite.blackbox.BlackBoxEngine$expressionEvaluation$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at io.infinite.blackbox.AllTests.run(AllTests.groovy:351)
	at io.infinite.blackbox.AllTests$run.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at io.infinite.blackbox.AllTests.main(AllTests.groovy:72)
```

**Comment by apryamostanov** [comment]
This happens because in dynamic compilation static method calls take precedence over instance methods with same name (Groovy supports static and instance methods with same name).
As suggested by [Wololock](https://groovy-community.slack.com/team/U8V6X52RX), using @StaticCompilation on unit performing closure calling can calling instance methods properly as expected.
