### ISSUE TITLE
Inner Class qualified **this** runtime class cast exception

### ISSUE THREAD

**Issue by apryamostanov** [INFINITE-TECHNOLOGY/BLACKBOX#9]
The below code fails in runtime:
```groovy
package io.infinite.blackbox.others

import io.infinite.blackbox.BlackBox
import io.infinite.blackbox.BlackBoxLevel

class ThisInner implements Runnable{

    class InnerClass {

        @BlackBox(blackBoxLevel = BlackBoxLevel.EXPRESSION)
        String foo() {
            ThisInner this2 = ThisInner.this
            return this2
        }

    }

    @Override
    String toString() {
        return "Outer"
    }

    @Override
    void run() {
        System.out.println(new InnerClass().foo())
    }
}
```

Exception:
```
Caught: java.lang.ClassCastException: io.infinite.blackbox.others.ThisInner$InnerClass cannot be cast to io.infinite.blackbox.others.ThisInner$InnerClass$_foo_closure1
java.lang.ClassCastException: io.infinite.blackbox.others.ThisInner$InnerClass cannot be cast to io.infinite.blackbox.others.ThisInner$InnerClass$_foo_closure1
	at io.infinite.blackbox.others.ThisInner$InnerClass$_foo_closure1$_closure2.doCall(ThisInner.groovy)
	at io.infinite.blackbox.BlackBoxEngine.expressionEvaluation(BlackBoxEngine.groovy:153)
	at io.infinite.blackbox.BlackBoxEngine$expressionEvaluation$3.call(Unknown Source)
	at io.infinite.blackbox.others.ThisInner$InnerClass$_foo_closure1.doCall(ThisInner.groovy:12)
	at io.infinite.blackbox.others.ThisInner$InnerClass$_foo_closure1.doCall(ThisInner.groovy)
	at io.infinite.blackbox.BlackBoxEngine.executeMethod(BlackBoxEngine.groovy:325)
	at io.infinite.blackbox.BlackBoxEngine$executeMethod$1.call(Unknown Source)
	at io.infinite.blackbox.others.ThisInner$InnerClass.foo(ThisInner.groovy)
	at io.infinite.blackbox.others.ThisInner$InnerClass$foo.call(Unknown Source)
	at io.infinite.blackbox.others.ThisInner.run(ThisInner.groovy:25)
```

**Comment by apryamostanov** [comment]
https://issues.apache.org/jira/browse/GROOVY-8881
